apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterpedia.internalstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  internalstorage-config.yaml: |-
    type: {{ include "clusterpedia.storage.type" . | quote }}
    host: {{ include "clusterpedia.storage.host" . | quote }}
    port: {{ include "clusterpedia.storage.port" . }}
    user: {{ include "clusterpedia.storage.user" . }}
    database: {{ include "clusterpedia.storage.database" . }}
    {{- if .Values.log.enabled }}
    log:
      stdout: {{ .Values.log.stdout }}
      level: {{ .Values.log.level | quote }}
      slowThreshold: {{ .Values.log.slowThreshold }}
      ignoreRecordNotFoundError: {{ .Values.log.ignoreRecordNotFoundError }}
    {{- end -}}
