apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterpedia.storage.override.configmap.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |-
    type: "mysql"
    host: {{ include "clusterpedia.mysql.storage.host" . | quote }}
    port: {{ include "clusterpedia.mysql.storage.port" . }}
    user: {{ include "clusterpedia.mysql.storage.user" . }}
    database: {{ include "clusterpedia.mysql.storage.database" . }}
    {{- if .Values.storageConfig.log.enabled }}
    log:
      stdout: {{ .Values.storageConfig.log.stdout }}
      level: {{ .Values.storageConfig.log.level | default "Warn" | quote }}
      slowThreshold: {{ .Values.storageConfig.log.slowThreshold }}
      ignoreRecordNotFoundError: {{ .Values.storageConfig.log.ignoreRecordNotFoundError }}
      logger:
        filename: {{ .Values.storageConfig.log.logger.filename }}
        maxsize: {{ .Values.storageConfig.log.logger.maxsize }}
        maxbackups: {{ .Values.storageConfig.log.logger.maxbackups }}
    {{- end }}
    connPool:
      maxIdleConns: {{ .Values.storageConfig.connPool.maxIdleConns | int }}
      maxOpenConns: {{ .Values.storageConfig.connPool.maxOpenConns | int }}
      connMaxLifetime: {{ .Values.storageConfig.connPool.connMaxLifetime }}
